encyclopedia/urls.py
from django.urls import path

from . import views
from . import util

app_name = 'encyclopedia'

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search_encyclopedia, name="search"),
    path("create_page", views.createpage, name="create_page"),
    path("wiki/<str:title>", views.show_page, name="get_page"),
    path("kekW", views.randompage, name="random")

]

    

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms.py
from django import forms

class entryForm(forms.Form):
    title = forms.CharField(label="title")
    content = forms.CharField(label="content")

class editbtnForm(forms.Form):
    button = forms.BooleanField(label="Edit", required="False")

encyclopedia/views.py
from django.forms.forms import Form
from django.http.response import HttpResponseRedirect
from encyclopedia.forms import entryForm
from django.shortcuts import render
from . import util, forms
import re
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django import forms
import random

import encyclopedia

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def show_page(request, title):
    page_info = util.get_entry(title)
    edit_btn = forms.Form(forms.BooleanField(label="Edit", required="False"))
    if show_page is None:
        if edit_btn == True:
            return render(request, "encyclopedia/createpage.html")
        else:
            return render(request, "encyclopedia/error.html")
    return render(request, "encyclopedia/title.html", {
        "info" : page_info,
        "title" : title,  
        "btn" : edit_btn
    })



def search_encyclopedia(request):
    if request.method =="GET":
        searched = request.GET['q']
        entries = util.get_entry(searched)
        if searched == entries:
            return render(request, "encyclopedia/search-page.html", {
                "searched" : searched,
                "entry" : searched 
            })
        else:
            entries = util.list_entries()
            result = ["Nothing Found!"]
            test = "this is a test"
            searched = request.GET['q']
            for entry in entries:
                if searched.lower() in entry.lower():
                    result = entry
            return render(request, "encyclopedia/search-page.html", {
                "entry" : result, 
                "searched" : searched 
            })

#why my shit no working?



def createpage(request):
    form = entryForm()
    if request.method == "POST":
        form = entryForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            title = form.cleaned_data['title']
            entries = util.list_entries()
            if title not in entries:
                util.save_entry(title, content)
                return render(request, "encyclopedia/title.html", {
                    "title" : title
                })
            else:
                return render(request, "encyclopedia/error.html", {
                "error" : "else1"
                })
        else:
            return render(request, "encyclopedia/error.html")
    else: 
        return render(request, "encyclopedia/createpage.html", {
            "form" : form
        })
    

def randompage(request):
    entries = util.list_entries()
    title = random.choice(entries)
    page_info = util.get_entry(title)
    return render(request, "encyclopedia/title.html", {
        "title" : title,
        "info" : page_info
    })

encyclopedia/templates/encyclopedia/createerror.html
{% extends "encyclopedia/layout.html" %}
{% block title %}Error Creating Page!{% endblock %}

{% block body %}
    <h4>Error! Page Already Exist!</h4>
{% endblock %}

encyclopedia/templates/encyclopedia/createpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Create a New Page!{% endblock %}

{% block body %}
    <h4>
        <form action="{% url 'encyclopedia:create_page' %}" method="POST">\
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    </h4>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}Page Not Found!{% endblock %}

{% block body %}
    <h1>Page Not Found!</h1>
    <h4>Did You Enter a Proper url></h4>
    <h4>{{ error }}</h4>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:get_page' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    {% csrf_token %}
                    <input action="{% url 'encyclopedia:search' %}" method="GET" class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>   
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div> 
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}  
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{ title }}  {% endblock %}

encyclopedia/templates/encyclopedia/search-page.html
{% extends "encyclopedia/layout.html" %}

{% block title %} 
    Search Results
{% endblock %}

{% block nav %} 
{% endblock %}

{% block body %}
    <center>
        {% if searched %}
            <h1 id="result">Results for: {{ searched }}</h1>
            <dl>
                <li><a href="{% url 'encyclopedia:get_page' title=entry %}">{{ entry }}</a></li>
            </dl>
        {% else %}
            <h1>Please use the search bar</h1>
        {% endif %}
    </center>
    
{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %} {{ title }} {% endblock %}

{% block body %} 
{{ btn }}

{{ info }} 
{% endblock %}